{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Python 有两种错误很容易辨认：语法错误和异常。\n",
    "Python assert（断言）用于判断一个表达式，在表达式条件为 false 的时候触发异常。\n",
    "\n",
    "\n",
    "异常处理\n",
    "try/except\n",
    "\n",
    "try: { 执行代码}\n",
    "except: {发生异常执行的代码}\n",
    "    \n",
    "#测试代码\n",
    "while True:\n",
    "    try:\n",
    "        x = int(input(\"请输入一个数字: \"))\n",
    "        break\n",
    "    except ValueError:\n",
    "        print(\"您输入的不是数字，请再次尝试输入！\")\n",
    "\n",
    "    \n",
    "try/except...else\n",
    "else 子句将在 try 子句没有发生任何异常的时候执行\n",
    "\n",
    "try: { 执行代码}\n",
    "except: {发生异常执行的代码}\n",
    "else: {没有异常执行的代码}\n",
    "    \n",
    "#测试代码    \n",
    "for arg in sys.argv[1:]:\n",
    "    try:\n",
    "        f = open(arg, 'r')\n",
    "    except IOError:\n",
    "        print('cannot open', arg)\n",
    "    else:\n",
    "        print(arg, 'has', len(f.readlines()), 'lines')\n",
    "        f.close()\n",
    "        \n",
    "#测试代码，特定错误打印\n",
    "def this_fails():\n",
    "    x = 1/0\n",
    "if __name__ == '__main__'   \n",
    "try:\n",
    "    this_fails()\n",
    "except ZeroDivisionError as err:\n",
    "    print('Handling run-time error:', err)\n",
    "   \n",
    "\n",
    "try/except...else...finally\n",
    "try: { 执行代码}\n",
    "except: {发生异常执行的代码}\n",
    "else: {没有异常执行的代码}\n",
    "finally: {不管有没有异常都执行的代码}\n",
    "    \n",
    "    \n",
    "#测试代码：\n",
    "try:\n",
    "    runoob()\n",
    "except AssertionError as error:\n",
    "    print(error)\n",
    "else:\n",
    "    try:\n",
    "        with open('file.log') as file:\n",
    "            read_data = file.read()\n",
    "    except FileNotFoundError as fnf_error:\n",
    "        print(fnf_error)\n",
    "finally:\n",
    "    print('这句话，无论异常是否发生都会执行。')\n",
    "    \n",
    "    \n",
    "抛出异常\n",
    "Python 使用 raise 语句抛出一个指定的异常。\n",
    "raise [Exception [, args [, traceback]]]\n",
    "\n",
    "raise -----》Exception\n",
    "\n",
    "\n",
    "#测试代码\n",
    "x = 10\n",
    "if x > 5:\n",
    "    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))\n",
    "\n",
    "raise 唯一的一个参数指定了要被抛出的异常。它必须是一个异常的实例或者是异常的类（也就是 Exception 的子类）。\n",
    "\n",
    "如果你只想知道这是否抛出了一个异常，并不想去处理它，那么一个简单的 raise 语句就可以再次把它抛出\n",
    "\n",
    "try:\n",
    "    raise NameError('HiThere')\n",
    "except NameError:\n",
    "    print('An exception flew by!')\n",
    "    raise\n",
    "   \n",
    "\n",
    "用户自定义异常\n",
    "你可以通过创建一个新的异常类来拥有自己的异常。异常类继承自 Exception 类，可以直接继承，或者间接继承，例如:\n",
    "    \n",
    ">>> class MyError(Exception):\n",
    "        def __init__(self, value):\n",
    "            self.value = value\n",
    "        def __str__(self):\n",
    "            return repr(self.value)\n",
    "   \n",
    ">>> try:\n",
    "        raise MyError(2*2)\n",
    "    except MyError as e:\n",
    "        print('My exception occurred, value:', e.value)\n",
    "        \n",
    "# 在这个例子中，类 Exception 默认的 __init__() 被覆盖。\n",
    "# 当创建一个模块有可能抛出多种不同的异常时，一种通常的做法是为这个包建立一个基础异常类，然后基于这个基础类为不同的错误情况创建不同的子类:\n",
    "\n",
    "class Error(Exception):\n",
    "    \"\"\"Base class for exceptions in this module.\"\"\"\n",
    "    pass\n",
    "\n",
    "class InputError(Error):\n",
    "    \"\"\"Exception raised for errors in the input.\n",
    "\n",
    "    Attributes:\n",
    "        expression -- input expression in which the error occurred\n",
    "        message -- explanation of the error\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, expression, message):\n",
    "        self.expression = expression\n",
    "        self.message = message\n",
    "\n",
    "class TransitionError(Error):\n",
    "    \"\"\"Raised when an operation attempts a state transition that's not\n",
    "    allowed.\n",
    "\n",
    "    Attributes:\n",
    "        previous -- state at beginning of transition\n",
    "        next -- attempted new state\n",
    "        message -- explanation of why the specific transition is not allowed\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, previous, next, message):\n",
    "        self.previous = previous\n",
    "        self.next = next\n",
    "        self.message = message\n",
    "        \n",
    "        \n",
    "#定义清理行为\n",
    ">>> try:\n",
    "...     raise KeyboardInterrupt\n",
    "... finally:\n",
    "...     print('Goodbye, world!')\n",
    "\n",
    "\n",
    "#Python的错误其实也是class，所有的错误类型都继承自BaseException，所以在使用except时需要注意的是，\n",
    "# 它不但捕获该类型的错误，还把其子类也“一网打尽”。比如\n",
    "\n",
    "# try:\n",
    "#     foo()\n",
    "# except ValueError as e:\n",
    "#     print('ValueError')\n",
    "# except UnicodeError as e:\n",
    "#     print('UnicodeError')\n",
    "\n",
    "# 第二个except永远也捕获不到UnicodeError，因为UnicodeError是ValueError的子类，如果有，也被第一个except给捕获了。\n",
    "# Python所有的错误都是从BaseException类派生的，常见的错误类型和继承关系看这里：\n",
    "\n",
    "#https://docs.python.org/3/library/exceptions.html#exception-hierarchy\n",
    "# BaseException\n",
    "#  +-- SystemExit\n",
    "#  +-- KeyboardInterrupt\n",
    "#  +-- GeneratorExit\n",
    "#  +-- Exception\n",
    "#       +-- StopIteration\n",
    "#       +-- StopAsyncIteration\n",
    "#       +-- ArithmeticError\n",
    "#       |    +-- FloatingPointError\n",
    "#       |    +-- OverflowError\n",
    "#       |    +-- ZeroDivisionError\n",
    "#       +-- AssertionError\n",
    "#       +-- AttributeError\n",
    "#       +-- BufferError\n",
    "#       +-- EOFError\n",
    "#       +-- ImportError\n",
    "#       |    +-- ModuleNotFoundError\n",
    "#       +-- LookupError\n",
    "#       |    +-- IndexError\n",
    "#       |    +-- KeyError\n",
    "#       +-- MemoryError\n",
    "#       +-- NameError\n",
    "#       |    +-- UnboundLocalError\n",
    "#       +-- OSError\n",
    "#       |    +-- BlockingIOError\n",
    "#       |    +-- ChildProcessError\n",
    "#       |    +-- ConnectionError\n",
    "#       |    |    +-- BrokenPipeError\n",
    "#       |    |    +-- ConnectionAbortedError\n",
    "#       |    |    +-- ConnectionRefusedError\n",
    "#       |    |    +-- ConnectionResetError\n",
    "#       |    +-- FileExistsError\n",
    "#       |    +-- FileNotFoundError\n",
    "#       |    +-- InterruptedError\n",
    "#       |    +-- IsADirectoryError\n",
    "#       |    +-- NotADirectoryError\n",
    "#       |    +-- PermissionError\n",
    "#       |    +-- ProcessLookupError\n",
    "#       |    +-- TimeoutError\n",
    "#       +-- ReferenceError\n",
    "#       +-- RuntimeError\n",
    "#       |    +-- NotImplementedError\n",
    "#       |    +-- RecursionError\n",
    "#       +-- SyntaxError\n",
    "#       |    +-- IndentationError\n",
    "#       |         +-- TabError\n",
    "#       +-- SystemError\n",
    "#       +-- TypeError\n",
    "#       +-- ValueError\n",
    "#       |    +-- UnicodeError\n",
    "#       |         +-- UnicodeDecodeError\n",
    "#       |         +-- UnicodeEncodeError\n",
    "#       |         +-- UnicodeTranslateError\n",
    "#       +-- Warning\n",
    "#            +-- DeprecationWarning\n",
    "#            +-- PendingDeprecationWarning\n",
    "#            +-- RuntimeWarning\n",
    "#            +-- SyntaxWarning\n",
    "#            +-- UserWarning\n",
    "#            +-- FutureWarning\n",
    "#            +-- ImportWarning\n",
    "#            +-- UnicodeWarning\n",
    "#            +-- BytesWarning\n",
    "#            +-- ResourceWarning"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
